runtime: php



env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:2LrePy2t1dPskZ5nD7VYW0FoDFx0cfdZNj+WgiygBW4=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  APP_DEBUG: true
  APP_LOG_LEVEL: debug
  APP_URL: http://localhost
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: whiteapp-28a36:europe-west3:whiteapp
  DB_USERNAME: root
  DB_PASSWORD: fgEfERGER24RG!"
  DB_SOCKET: /cloudsql/whiteapp-28a36:europe-west3:whiteapp
  BROADCAST_DRIVER: log
  CACHE_DRIVER: database
  SESSION_LIFETIME: 120
  QUEUE_DRIVER: sync
  MAIL_DRIVER: mailgun
  MAILGUN_DOMAIN: sandboxd918c4e20e5f4cc59776a4aceb5817c4.mailgun.org
  MAILGUN_SECRET: ${{ secrets.MAILGUN_SECRET }}
  MAIL_USERNAME: postmaster@sandboxd918c4e20e5f4cc59776a4aceb5817c4.mailgun.org
  MAIL_PASSWORD: 9d66b91818c3f4ca4713aadba32b8843-52b0ea77-0945b295
env: flex     # let app engine know we use flexible environment
runtime_config:
  document_root: public   #folder where index.php is
# Ensure we skip ".env", which is only for local development
beta_settings:
   # for Cloud SQL, set this value to the Cloud SQL connection name,
   # e.g. "project:region:cloudsql-instance"
   cloud_sql_instances: whiteapp-28a36:europe-west3:whiteapp
